### ISSUE TITLE
Bootstrap Everything

### ISSUE THREAD

**Issue by kirbyk** [lizixroy/Quizroom#4]
@DavisLWebb I've implemented the basic views for each page. You just need to go through and bootstrap all the pages. I've wrapper the application layout in a container div, feel free to change that as you feel necessary.

Let me know if you need any help. I love me some bootstrap.

**Comment by DavisLWebb** [comment]
Alright.  I've been working on the home page while waiting for everything else to be set up. I'll start working on the other pages now.

**Comment by kirbyk** [comment]
Feel free to make a PR and push as you make changes, and we just won't merge it in.

**Comment by DavisLWebb** [comment]
That is what I was just getting on to ask you how to do.  I've made a front page (super basic) that should be ready to connect to some pages that Im assuming we will have.  I'm not sure how to push properly though.  I figured I'd ask before I went and broke something

**Comment by kirbyk** [comment]
So you'll want to commit your changes onto your own branch. I'm going to assume you're not currently on your own branch. 




This also assumes nothing is added or commited.




git stash (stash you current changes)

git checkout -b bootstrap (create a new branch called bootstrap)

git stash pop (put your stashed changes on this new branch)

git add . (add your changes to the staging area)

git commit -m 'add bootstrap to front page' (commit your changes in the staging area)

git push origin bootstrap (origin is the name of the remote (github) bootstrap is the name of the branch, so your pushing bootstrap to github)




Now on GitHub you'll be prompted to make a PR out of the branch. Just follow the on screen instructions. 




Text me if you have issues.

**Comment by DavisLWebb** [comment]
I actually am on my own branch.  I think I called it DavisLWebb|UserInterface (or something like that).  Since I've already done that, Im assuming I can just start from the "git add" line?

**Comment by kirbyk** [comment]
Yup! You can use `git branch` to see all the branches.

**Comment by DavisLWebb** [comment]
Alright, Ill get that committed so I can pull the recent changes.

**Comment by DavisLWebb** [comment]
Should be pushed.  Getting off for the night.

**Comment by DavisLWebb** [comment]
Did we change something related to css? I can no longer change anything in the scss files without getting an error/getting no results.  Also, haml is super ugly.

**Comment by kirbyk** [comment]
You'll have to be more specific about the error you're getting. I can add styles to application.scss and see results fine.

**Comment by DavisLWebb** [comment]
Oh sorry, I figured it out.  I was just really really dumb.

**Comment by DavisLWebb** [comment]
I believe I have everything up properly now.  Bootstrap should be all over the place now.
